<<<<<<< HEAD
name: lint-on-push
=======
name: Linter
>>>>>>> cf2772fab0af5573da775e7437e6acdca424f26e

on:
  - push
  - pull_request

jobs:
  lint-python:
    name: ruff
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: checkout-code
        uses: actions/checkout@v3
<<<<<<< HEAD
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: pip
          cache-dependency-path: requirements.txt
      - name: install-pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: pre-commit
        uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
        with:
          msg: apply code formatting and linting auto-fixes
      - name: test-startup
        run: |
          export COMMANDLINE_ARGS="--debug --test"
          python launch.py
=======
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          # NB: there's no cache: pip here since we're not installing anything
          #     from the requirements.txt file(s) in the repository; it's faster
          #     not to have GHA download an (at the time of writing) 4 GB cache
          #     of PyTorch and other dependencies.
      - name: Install Ruff
        run: pip install ruff==0.1.6
      - name: Run Ruff
        run: ruff .
  lint-js:
    name: eslint
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i --ci
      - run: npm run lint
>>>>>>> cf2772fab0af5573da775e7437e6acdca424f26e
